import type { Metadata } from "next";
import { Geist, Geist_Mono,DM_Sans, Lora, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SmallNavbar from "@/components/SmallNavbar";
import SiteFooter from "@/components/site-footer";
import Comments from "@/components/Comments";
import { getUser } from "./_actions/action";
export const dynamic = 'force-dynamic'; // <-- Added this line
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const lora = Lora({
  variable: "--font-Lora",
  subsets: ["latin"],
});
const dm_sans = DM_Sans({
  variable: "--font-DM_Sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const oswald = Oswald({
  variable: "--font-Oswald",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  let userData = await getUser();




  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${lora.variable} ${oswald.variable} ${geistMono.variable} ${dm_sans.variable} antialiased`}
      >
           
        <Navbar userData={userData} />
        <SmallNavbar  userData={userData} />
        
     
        {children}
        <Toaster />
        <SiteFooter/>
      </body>
    </html>
  );
}
