import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import Header from "@/components/Header";
export const dynamic = 'force-dynamic'; // <-- Added this line

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>

            {/* Sidebar */}
            <AppSidebar />

            {/* Main content area */}
            <SidebarInset className="flex-1 flex flex-col w-full min-w-0">
              {/* Header */}

              <Header />

              {/* Page content */}
              <div className="flex-1 mt-10 overflow-auto w-full">
                {children}
              </div>
            </SidebarInset>
            <Toaster />
        </SidebarProvider>
      </body>
    </html>
  );
}
